### ISSUE TITLE
Incorrect Pins Reference for Meadow I2C

### ISSUE THREAD

**Issue by csuski** [WildernessLabs/Documentation#125]
On the Meadow I2C page - http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/Digital/Protocols/I2C/

it says the I2C pins are D06 and D07 in the text and in the picture.

The correct pins are D7 and D08.

**Comment by csuski** [comment]
This is fixed in the latest documentation.

**Comment by bryancostanich** [comment]
Thanks!
