### ISSUE TITLE
Online doc visual show VS2017

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Documentation#131]
the online stuff shows VS 2017 screen shots, but searching for extensions with 'meadow' in VS2017 returns nothing.
Downloading the extension and running it seems to allow only VS2019.  The docs should be more clear on that (the text says 2019, but the screen caps are definitely 2017)

**Comment by jorgedevs** [comment]
I'll look up for these screenshots to update them to VS2019.

**Comment by jorgedevs** [comment]
Closing this issue. Only VS2017 (for Mac) screenshot I saw in the Assets folder is for Netduino Getting Started. For Meadow we're in the clear.
