### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by davemclaughlin** [WildernessLabs/Documentation#144]
The following links to CAN and I2S are broken.

http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/Digital/Protocols/CAN

http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/Digital/Protocols/I2S

on this page

http://beta-developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/

**Comment by jorgedevs** [comment]
Hi @davemclaughlin, thanks for reporting this. I have removed the links from the list, and we'll re-add them once the protocols are implemented.
