### ISSUE TITLE
--GetDeviceInfo faulty argument description

### ISSUE THREAD

**Issue by MaxMommersteeg** [WildernessLabs/Documentation#160]
Ran the Meadow.CLI tool and noticed that `--MonoEnable` and `--GetDeviceInfo` have the exact same argument description, which I think is questionable:
![image](https://user-images.githubusercontent.com/9657173/71365483-6dc6e300-259f-11ea-8b8d-5aacacdbd377.png)

I tried to find the CLI's GitHub repository to correct it, but couldn't find where it was located.

**Comment by bryancostanich** [comment]
fixed.
