### ISSUE TITLE
Missing wiring example screenshot for ADXL345 sensor

### ISSUE THREAD

**Issue by lukaszch** [WildernessLabs/Documentation#171]
There is a missing wiring example screenshot for ADXL345 sensor on the documentation page http://developer.wildernesslabs.co/docs/api/Meadow.Foundation/Meadow.Foundation.Sensors.Motion.Adxl345.html#wiring-example

**Comment by adrianstevens** [comment]
@lukaszch thank you for reporting the missing image - it's no fixed and will go live with the next release
