### ISSUE TITLE
Meadow.OS source code link?

### ISSUE THREAD

**Issue by andreymrt** [WildernessLabs/Documentation#187]
Are there any plans to release Meadow.OS?
Mostly looking to add ISR hooks.

**Comment by bryancostanich** [comment]
Not in the near term. Let us know what you're looking to do and maybe we can help.

**Comment by andreymrt** [comment]
I was looking for using it in a realtime application. My Meadow related baseline was netduino, which had a ton of overhead and was unsuitable for handling repetitive interrupts in under 100us

**Comment by bryancostanich** [comment]
Gotcha. Meadow is currently unsuitable for hard realtime applications. However, we're in progress with Ahead of Time (AoT) compilation and we plan on shipping APIs and guidance around realtime stuff in the future.
