### ISSUE TITLE
Typo in page about atoms

### ISSUE THREAD

**Issue by panos-parisis** [WildernessLabs/Documentation#193]
In http://developer.wildernesslabs.co/Hardware/Tutorials/Electronics/Part1/Atoms/ I think that the phrase "Iron, which an atomic number of 26, should naturally have 26 protons, and 26 neutrons." should be "Iron, which an atomic number of 26, should naturally have 26 protons, and 26 electrons."

**Comment by jorgedevs** [comment]
Hello @panos-parisis, thanks for reporting this issue. You're right, Iron has 26 protons and 26 electrons. This has been corrected.
