### ISSUE TITLE
Documentation error - LEDApp example code - override Run - no suitable method found to override

### ISSUE THREAD

**Issue by beckerts** [WildernessLabs/Documentation#203]
There is an error in the Meadow Applications - Meadow Basics documentation.
http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Apps/

The example code under the Sample Meadow Application section shows to override the IApp Run() method.
The IApp interface does not contain a void Run() method.
Visual Studio Error: 'LEDApp.Run()': no suitable method found to override

class LEDApp : App<F7Micro, LEDApp>
{
    private IDigitalOutputPort redLed;
    private IDigitalOutputPort blueLed;
    private IDigitalOutputPort greenLed;

    public override void Run()
    {
        CreateOutputs();
        ShowLights();
    }

Using package
Meadow.Foundation (0.15.2)
Meadow assembly Version 0.13.0.0
MeadowOS Version: 0.3.11 (May 22 2020 21:40:16)

**Comment by jorgedevs** [comment]
Hello @beckerts, thanks for reporting and apologies for not taking a look at this sooner. If you revisit these docs, you'll see that the mix-up has been corrected, as Meadow Apps no longer have a Run method.
