### ISSUE TITLE
Installation via VS-Extension doesn't work & Documentation is confusing

### ISSUE THREAD

**Issue by crone66** [WildernessLabs/Documentation#206]
Hi, I tried to install the os like described in the documentation. The output window just shows "Device not found. Connect the device in bootloader mode by plugging in the device while holding down the BOOT button."

I have never used the dfu-util before. The device was shown as STM32 BOOTLOADER (with a warning sign) in device manager. Uninstalling the device didn't help and there was not check box to uninstall drivers.

I managed to install the OS with dfu-util and Zadig successfully but there is something wrong with the extension.

**I know that most of the readers would understand the installation documentation with dfu-util tool, but inexperienced users might have a problem. Therefore, I've created a list of everything that I noticed, which could be improved:**

1. The command  "dfu-util -a 0 -S [DEVICE_SERIAL] -D Meadow.OS.bin -s 0x08000000" should not be on the right side of the website. I was looking for this command a few minutes and I read the entire text multiple times until I realized the command is on the right side. **The command should be within the text especially since all other command are within the text too.**

2. After the OS was installed the documentation explains that some Meadow CLI commands must be executed. 
The commands are only for linux/mac os because under windows **mono** and the described device path (**/dev/tty.usbmodem01**) wouldn't work.
For Windows a command like "mono ./Meadow.CLI/Meadow.CLI.exe -s **/dev/tty.usbmodem01** --MonoDisable" should look like this "Meadow.CLI\Meadow.CLI.exe -s **COM8** --MonoDisable"
Users who don't know what mono is might think that they need mono or that this command must only be executed under linux/mac

3. The highlighted device port of a command should be replaced with a placeholder.
-s [DEVICEPORT]

4. After a restart (which should be done as the documentation says) the command "mono ./Meadow.CLI/Meadow.CLI.exe --WriteFile -f Meadow.OS.Runtime.bin --KeepAlive" should be executed but the "-s" argument is missing and by default it is trying to use "/dev/tty.usbmodem01" which doesn't work under Windows.

5. Besides that, the user should press space to exit for Windows the user has to press enter.

**Comment by jorgedevs** [comment]
Hi @crone66 , apologies for not looking into this issue report sooner. If you've checked the [latest instructions to Deploy Meadow.OS](http://developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow/), you should fine them a lot easier to understand. I'm closing this issue for now, but dont hesitate to re-open it if you have any related concerns.
