### ISSUE TITLE
Link broken in Serial/UART

### ISSUE THREAD

**Issue by upswing1** [WildernessLabs/Documentation#216]
Link is broken at page

http://developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/Digital/Protocols/UART/

Additional APIs
There are a number of other APIs available on serial ports, please see the **ISerialPort API documentation** for more details.

http://beta-developer.wildernesslabs.co/docs/api/Meadow/Meadow.Hardware.ISerialPort.html  
404 not found

**Comment by jorgedevs** [comment]
Hi @upswing1, thanks for reporting this issue! The link has now been fixed.
