### ISSUE TITLE
VS 2019 Meadow.OS Install Does NOT work

### ISSUE THREAD

**Issue by ivanfarkas2** [WildernessLabs/Documentation#218]
# VS 2019 Meadow.OS Install Does NOT work
**Click Flash Device**
Error:
```
[11/20/2020 7:51:47 PM] Begin 'Flash Device'
[11/20/2020 7:51:47 PM] Device not found. Connect the device in bootloader mode by plugging in the device while holding down the BOOT button.
[11/20/2020 7:51:47 PM] For more help, visit http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Troubleshooting/VisualStudio/
```
Link remedy DOES NOT work, perhaps outdated, like the rest of the documentation or that is expected from a beta release.
I was forced to do **[Flashing the Meadow with the latest OS via Device Firmware Upgrade (DFU).](http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Troubleshooting/VisualStudio/)**, that is incorrect for Windows

**The correct commands:**

```
dfu-util --list

dfu-util -a 0 -S [serial#] -D Meadow.OS.bin -s 0x08000000

# Reset F7 - press the reset (RST) button.

# Disable mono
Meadow.CLI\Meadow.CLI.exe -s COM3 --MonoDisable

# Reset F7 - press the reset (RST) button.

# Upload new Mono Runtime:
Meadow.CLI\Meadow.CLI.exe --WriteFile -f Meadow.OS.Runtime.bin

# Move the runtime into it’s special home on the 2MB partition:
Meadow.CLI\Meadow.CLI.exe --MonoFlash

# Reset F7 - press the reset (RST) button.

# Upload the ESP32 bootloader: (note progress percentage may be incorrect)
Meadow.CLI\Meadow.CLI.exe --Esp32WriteFile -f bootloader.bin --McuDestAddr 0x1000

# Reset F7 - press the reset (RST) button.

# Upload the ESP32 partition table:
Meadow.CLI\Meadow.CLI.exe --Esp32WriteFile -f partition-table.bin --McuDestAddr 0x8000

# Reset F7 - press the reset (RST) button.

# Upload the ESP32 Meadow Comms application:
Meadow.CLI\Meadow.CLI.exe --Esp32WriteFile -f MeadowComms.bin --McuDestAddr 0x10000

```

**Comment by jorgedevs** [comment]
Hello @ivanfarkas2, thanks for reporting this issue! As of beta 4.2 release, we removed the Flashing Device function from the VS Extension on Windows and we revamped the CLI so the flashing process is way simpler now. For those reasons, I'm going to close this issue, but feel free to open a new issue if you have any hiccups with the new flashing process.

http://developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow/

Thanks,
Jorge
