### ISSUE TITLE
VS 2019 Preview - Project Template Is Missing

### ISSUE THREAD

**Issue by ivanfarkas2** [WildernessLabs/Documentation#220]
# VS 2019 Preview - Project Template missing

##  VS 2019 Preview - Project Template - missing
![VS 2019 Preview - Project Template](https://user-images.githubusercontent.com/53225260/99880795-91494200-2be3-11eb-996d-19cab44c4bd3.png)

## VS 2019 - Project Template - OK
![VS 2019 - Project Template](https://user-images.githubusercontent.com/53225260/99880753-50512d80-2be3-11eb-8dd4-9be866d969ba.png)

**Comment by jorgedevs** [comment]
Hello @ivanfarkas2, we currently have no plans on supporting the Meadow Extension on VS Preview. Sorry about that, we could revisit sometime in the future, but our hands are currently full with other tasks at the moment.
