### ISSUE TITLE
Meadow VS Extension Stuck

### ISSUE THREAD

**Issue by crone66** [WildernessLabs/Documentation#222]
When using the Meadow VS Extension on Windows to flash the device the installation stucks at: `[DATETIME] Initialize device (~30s)`
If I press the reset button on the board the process continues. I figured out that sometimes a required reset command isn't executed or recognized. I could reproduce this behavior also on Flash Coprocessor, Check Version and during deployment of an app.

**Comment by bryancostanich** [comment]
Meadow deployment has changed significantly since this was filed and this issue should no longer occur.
