### ISSUE TITLE
[Typo] Word "eiter:" is spelt incorrectly

### ISSUE THREAD

**Issue by CartBlanche** [WildernessLabs/Documentation#223]
If you look here -
https://github.com/WildernessLabs/Documentation/blob/e898a4d4014d17d2f98880d5f2f395a86171d274/docs/Meadow/Getting_Started/index.md
on point 3 is says

"Deploy Meadow OS to your Board **eiter**"

should be **either**.

**Comment by jorgedevs** [comment]
Thanks for reporting! This has been corrected since b4.2.
