### ISSUE TITLE
Typo: scan instead of can

### ISSUE THREAD

**Issue by RudyMeijer** [WildernessLabs/Documentation#232]
Look at page: http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Networking/

Sentence: 
You can also can for WiFI networks via the Scan()

Replace second occurrence of word **can** with **scan**.

**Comment by lamebrain** [comment]
sync

**Comment by jorgedevs** [comment]
Thanks for reporting! The typo has been corrected.
