### ISSUE TITLE
Polling and events doc is empty

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#238]
here: http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/Working_w_Sensors/

**Comment by adrianstevens** [comment]
Update - it's using the wrong URL http://developer.wildernesslabs.co/Meadow/Meadow.Foundation/Working_with_Sensors/

**Comment by jorgedevs** [comment]
URL fixed in develop.
