### ISSUE TITLE
Device.WiFiAdapter.Connect always returns ConnectionStatus.Success

### ISSUE THREAD

**Issue by PaulNoto** [WildernessLabs/Documentation#240]
I was experimenting with the WiFi on Meadow today and discovered that Device.WiFiAdapter.Connect always returns ConnectionStatus.Success even with a Bad SSID or Password. I'm running Beta 4.4 of Meadow OS and using VS2019 with all current updates. I'm 99% sure this is a real issue. However, if I'm wrong, please let me know what I missed.
Thanks, Paul

**Comment by NevynUK** [comment]
This is a known bug and has been fixed in the next release.
