### ISSUE TITLE
System time always set to 1970

### ISSUE THREAD

**Issue by Dids** [WildernessLabs/Documentation#242]
Not entirely sure if this is more of a feature request than a bug submission, but as I couldn't find anything on the subject, I was wondering if syncing time via NTP (or even temporarily through the host while deploying) is a planned feature?

In my specific case, I'd need proper timestamps to be able to send RFC compliant syslog messages to remote logging facilities, but as I couldn't find a way (yet) to easily sync with an NTP server _and_ set the system time from that, I was hoping to get a more official comment on this, as I'm sure it will become more relevant for others in the future as well.

**Comment by NevynUK** [comment]
This is a planned feature.  At the time of writing the ESP32 can be configured to get the time from a server when the board is booting.  It does this successfully.

We still have the plumbing to install on the managed side to get this working.

I'm closing this issue as I'm sure we will highlight this in the release notes when it is wired up.
