### ISSUE TITLE
OS Deployment Docs assume new install

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Documentation#252]
The OS deployment docs section assumes you have nothing installed.  We need to cover update scenarios, too.

For example, the docs state:

> `Install Meadow.CLI: dotnet tool install WildernessLabs.Meadow.CLI --global`

However if you already installed and your local version is old, this won't update things.  You need to do this:

> `Install Meadow.CLI: dotnet tool update WildernessLabs.Meadow.CLI --global`

**Comment by patridge** [comment]
Should be fixed now. All three OS sections in the [Meadow OS Deployment page](http://developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow/#macos) appear to have the `dotnet tool update` command now.
