### ISSUE TITLE
Timer groups/channels are undocumented for PWM

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#254]
PWMs are created on timer groups and channels. multiple pins share the same group but are on different channels. 

all the PWMs on a single timer must share the same frequency, but can have different duty cycles. 

today, Meadow.Core enforces this and will throw an exception if you try to set competing frequencies on the same timer group, but no where in docs do we talk about the timer groups.

for source inspiration, we do document the interrupt groups.

we'll need to modify the pinout diagram, as well as add docs to describe.

**Comment by jorgedevs** [comment]
Done and available in the [PWM docs](http://developer.wildernesslabs.co/Meadow/Meadow_Basics/IO/Digital/PWM/)

**Comment by bryancostanich** [comment]
Awesome work, thanks, @jorgedevs !
