### ISSUE TITLE
Resistive sensor lab webpage broken

### ISSUE THREAD

**Issue by teknikal-wizard** [WildernessLabs/Documentation#271]
I was following the [resistive sensor lab](http://developer.wildernesslabs.co/Hardware/Tutorials/Electronics/Part5/Resistive_Sensor_Lab/) and found it cut off unexpectedly. 

I followed through to [the Github page](https://github.com/WildernessLabs/Documentation/blob/main/docs/Hardware/Tutorials/Electronics/Part5/Resistive_Sensor_Lab/index.md) and the rest of the content is there, so I am guessing the parser has broken when it tried to render the inline table or something.

**Comment by patridge** [comment]
This appears resolved at some point. Could be when we removed a funky Unicode character that showed up.
