### ISSUE TITLE
Favicon assets missing?

### ISSUE THREAD

**Issue by richardjharding** [WildernessLabs/Documentation#284]
Hard to find the dev site in a sea of tabs sometimes :) - looks like the icon links in the header point to various sizes eg

```http://developer.wildernesslabs.co/assets/favicon/favicon-196x196.png```

But they don't resolve to anything?

**Comment by patridge** [comment]
Looks like there are a bunch of files needed for this which vary based on platform, resolution, etc.

* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-57x57.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-114x114.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-72x72.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-144x144.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-60x60.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-120x120.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-76x76.png
* http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-152x152.png
* http://developer.wildernesslabs.co/assets/favicon/favicon-196x196.png
* http://developer.wildernesslabs.co/assets/favicon/favicon-96x96.png
* http://developer.wildernesslabs.co/assets/favicon/favicon-32x32.png
* http://developer.wildernesslabs.co/assets/favicon/favicon-16x16.png
* http://developer.wildernesslabs.co/assets/favicon/favicon-128.png
* http://developer.wildernesslabs.co/assets/favicon/mstile-144x144.png
* http://developer.wildernesslabs.co/assets/favicon/mstile-70x70.png
* http://developer.wildernesslabs.co/assets/favicon/mstile-150x150.png
* http://developer.wildernesslabs.co/assets/favicon/mstile-310x150.png
* http://developer.wildernesslabs.co/assets/favicon/mstile-310x310.png

That list is based on the source HTML from the root dev page.

```html
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="http://developer.wildernesslabs.co/assets/favicon/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="http://developer.wildernesslabs.co/assets/favicon/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="http://developer.wildernesslabs.co/assets/favicon/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="http://developer.wildernesslabs.co/assets/favicon/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="http://developer.wildernesslabs.co/assets/favicon/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="http://developer.wildernesslabs.co/assets/favicon/favicon-128.png" sizes="128x128" />
<meta name="application-name" content="Wilderness Labs Developer Portal"/>
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="http://developer.wildernesslabs.co/assets/favicon/mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="http://developer.wildernesslabs.co/assets/favicon/mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="http://developer.wildernesslabs.co/assets/favicon/mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="http://developer.wildernesslabs.co/assets/favicon/mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="http://developer.wildernesslabs.co/assets/favicon/mstile-310x310.png" />
```
