### ISSUE TITLE
Update Hello Meadow page w VS2022

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#286]

**Comment by CartBlanche** [comment]
Done!

**Comment by patridge** [comment]
@CartBlanche We still have #375 for the mobile workload changes, but did we publish whatever was fixed for this in the RC-1 merge to main?

**Comment by CartBlanche** [comment]
@patridge I've not investigated what we need to do to remove this workload requirement. I'd forgotten about it. I'll add it to my list of things to look at next week.

**Comment by patridge** [comment]
Since the follow up question has its own issue, closing this as resolved.
