### ISSUE TITLE
Servo.Core link

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#293]
The Servo.Core docs link point here:
http://developer.wildernesslabs.co/docs/api/Meadow.Foundation/Meadow.Foundation.Servos.ServoCore.html
Which is just a placeholder page

**Comment by patridge** [comment]
@adrianstevens Which Servo.Core docs page are you referencing?

I'm also having issues confusing when things should be ServoCore and when they should be [ServoBase](https://developer.wildernesslabs.co/docs/api/Meadow.Foundation/Meadow.Foundation.Servos.ServoBase.html), which has an API docs page.

**Comment by patridge** [comment]
I'm hoping ServoBase has replaced ServoCore and this issue is resolved now. Reopen as needed.
