### ISSUE TITLE
Getting Started - Docs should say get latest .NET

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#336]
rather than .NET 5, i think?

**Comment by bryancostanich** [comment]
we might also specify a note that says if you're on a mac m1, you'll need the Arm64, and x64 if you're on intel.

**Comment by patridge** [comment]
I've put together a draft PR to address this (#340), but waiting for confirmation before submitting it for review.

**Comment by bryancostanich** [comment]
yeah, i installed the .net 6 arm64 SDK on my m1

**Comment by patridge** [comment]
This should be deployed to production with the RC-1 docs publish.
