### ISSUE TITLE
Getting Started - Mac instructions say `brew install dfu-util` but no instruction to install brew

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#337]
we should probably add a line that says to install brew and link to some instructions

**Comment by bryancostanich** [comment]
instructions [here](https://brew.sh/)

**Comment by patridge** [comment]
Resolved in beta docs here: http://beta-developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow/#install-dfu-util-2

**Comment by patridge** [comment]
This was deployed to production with the RC-1 docs publish.
