### ISSUE TITLE
Review / fix MCPxxxxx docs

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#374]
The link from the [peripheral page](https://developer.wildernesslabs.co/Meadow/Meadow.Foundation/Peripherals/#ics) is broken on the main site

And I think we lost some details on the docs page (probably a file rename ...)

Addresses and such

**Comment by patridge** [comment]
I think these are working after some Docusaurus fun that @adunndevster2 handled. Feel free to reopen if you are still seeing something, @adrianstevens.
