### ISSUE TITLE
`Resolver` class needs documentation

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#390]
It's where you get access to the device and logger and such.

**Comment by patridge** [comment]
Initial outline proposal in branch: ap-resolve-doc
https://github.com/WildernessLabs/Documentation/blob/ap-resolver-doc/docs/Meadow/Meadow.OS/Resolver/index.md

**Comment by patridge** [comment]
Addressed in #786, currently deployed on dev and pending deployment to production.
https://developer.wildernesslabs.dev/Meadow/Meadow.OS/Resolver/

**Comment by patridge** [comment]
And...we're live.
https://developer.wildernesslabs.co/Meadow/Meadow.OS/Resolver/
