### ISSUE TITLE
Remove old setup page

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Documentation#400]
http://developer.wildernesslabs.co/Meadow/Getting_Started/Setup/

**Comment by patridge** [comment]
It looks like the macOS and Windows sub-pages are now just stubs to redirect back to the main Getting_Started page.

e.g., http://developer.wildernesslabs.co/Meadow/Getting_Started/Setup/macos/

@adrianstevens Do we want to continue that effort on this page?

**Comment by patridge** [comment]
Setup is still showing in the left-hand nav, though it is mostly redirecting now.

Possible approach:

* [ ] Remove left TOC **Setup** section
* [ ] Rework the root Setup page to point directly to the new pages rather than linking to pages that point to the new location
* [ ] Either...
    * [ ] Leave old setup pages with new location for anyone with old links
    * [ ] Add redirects to send folks to new locations directly

**Comment by patridge** [comment]
It looks like the TOC is just automatically happening when you load a page that isn't part of the usual sidebar system. So, removing that checklist item.
