### ISSUE TITLE
"Hello World" does not work on macOS

### ISSUE THREAD

**Issue by loicmorvan** [WildernessLabs/Documentation#402]
I followed the [Hello World example](http://developer.wildernesslabs.co/Meadow/Getting_Started/Hello_World/) on my Mac, but did not succeed.
I have installed Visual Studio 2022 for Mac Community, then installed the extension called "Meadow for VS2022".
At this installation step, VS tells me :
<img width="912" alt="Capture d’écran 2022-12-19 à 18 36 22" src="https://user-images.githubusercontent.com/678628/208486248-0b55f1fd-7002-4afa-870f-4988d979feb0.png">

I have verified that my install of VS2022 includes Xamarin: the documentation
 talks about "Mobile Development with .NET" but this option does not exist in VS2022 for Mac, instead I have the Android checked in the Xamarin section:
<img width="912" alt="Capture d’écran 2022-12-19 à 18 40 18" src="https://user-images.githubusercontent.com/678628/208486814-aaac6358-a87f-406a-9965-306122978a6b.png">

At this point, I'm not able to create a Meadow Application project: it does not appear in the "New project types".

**Comment by CartBlanche** [comment]
@loicmorvan Since Dec 2022 we've released v1..x of our extension. Is this still an issue for you or can we close this issue??

**Comment by loicmorvan** [comment]
I did not test it since a while... By the way visual studio for Mac will be discontinued soon, so I don't think this issue is worth it.

**Comment by CartBlanche** [comment]
@loicmorvan we are supporting VS4 Mac until August. We already have VSCode support for Mac working, which we'll encourage everyone on Mac to move to. 

I'll close this issue for now and if you still hit it using VS4M just reopen it.
