### ISSUE TITLE
WiFi docs are stale, indicating a return value for `Connect`

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Documentation#437]
http://developer.wildernesslabs.co/Meadow/Meadow.OS/Networking/

We no longer use legacy logic flow by returning a connection state but instead throw an exception if there's a problem.

**Comment by patridge** [comment]
This appears to have been resolved already.
<img width="584" alt="image" src="https://github.com/WildernessLabs/Documentation/assets/713665/ff557f4f-f5aa-43b5-b6c6-73069ca56a83">
