### ISSUE TITLE
docfx migration

### ISSUE THREAD

**Issue by lamebrain** [WildernessLabs/Documentation#440]
Sadly, our Jenkins server died, RIP. The scripts for generating the docs have been [migrated to actions](https://github.com/WildernessLabs/Documentation/blob/main/.github/workflows/jekyll-beta.yml), but the API docs are sadly outdated. Here's the script from the Jenkins job:
```
cd Documentation
cd docfx
docfx docfx.json
(cat .\docs\api\Meadow\toc.html) | % { $_ -replace ">Meadow.Peripherals.", ">" } > .\docs\api\Meadow\toc.html
(cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">Meadow.Foundation.", ">" } > .\docs\api\Meadow.Foundation\toc.html
(cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">/a>", ">Meadow.Foundation</a>" } > .\docs\api\Meadow.Foundation\toc.html
cd ../docs
bundle install
bundle exec jekyll build
cp ../docfx/docs ./_site -r
aws s3 sync _site s3://developer.wildernesslabs.co --delete
```
(The jekyll portion isn't needed)

For this to work, Meadow and Meadow.Foudation repos need to be pulled as siblings.

**Comment by CartBlanche** [comment]
@lamebrain So is the idea we'll have a api-doc.yml in this repo, that will contain the the docfx command calls?

**Comment by lamebrain** [comment]
When there is a change made in Meadow or Meadow.Foundation, we need clone the repo as a sibling, run the `docfx docfx.json` command, and copy the output the developer site.

**Comment by lamebrain** [comment]
maybe @patridge could help with this too?

**Comment by patridge** [comment]
This was added in #493 and others.
