### ISSUE TITLE
Links to Nowhere

### ISSUE THREAD

**Issue by davisar** [WildernessLabs/Documentation#484]
Several links on this page appear to go to nowhere: http://developer.wildernesslabs.co/Hardware/

Dead links include:
http://developer.wildernesslabs.co/Hardware/Reference/Components/LEDs/Driving_w_Resistor/
http://developer.wildernesslabs.co/Hardware/Reference/Components/LEDs
https://developer.wildernesslabs.co/Hardware/Reference/Components/LEDs/Driving_w_PWM/

**Comment by patridge** [comment]
Confirmed fixed on beta docs.
http://beta-developer.wildernesslabs.co/Hardware/
e.g., link to LED w/ PWM
http://beta-developer.wildernesslabs.co/Hardware/Circuits/Components/LEDs/Driving_w_PWM/
