### ISSUE TITLE
Change URL to the Meadow VS Extension in Hello World

### ISSUE THREAD

**Issue by jorgedevs** [WildernessLabs/Documentation#548]
In the Hello, Meadow! page. there's a changes we need to do here:

 - Since we dropped support for Visual Studio 2019, we should only word things pointing only to Visual Studio 2022
 - In the `Install the Meadow Extension` section, the URL to download said extension is pointing to the version compatible with VS2019, whereas we want to point readers to install the VS2022 extension. 

![image](https://github.com/WildernessLabs/Documentation/assets/3408668/5f3612dc-a628-4151-ac35-6aa597812361)

The file to do said changes is this one: https://github.com/WildernessLabs/Documentation/blob/main/docs/Meadow/Getting_Started/Hello_World/index.md

**Comment by patridge** [comment]
Thank you, @AlexHedley. While the direct issue is resolved, I spun off a new PR for a few more 2019 references (#597).
