### ISSUE TITLE
More warnings about charge-only USB cables

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/Documentation#549]
There is a warning about charge-only (no-data) USB cables in the [Troubleshooting page](https://developer.wildernesslabs.co/Meadow/Meadow_Basics/Troubleshooting/#usb-cables), but it would be nice to have a version of that on the [Meadow OS Deployment page](https://developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow/) as well, possibly under each OS when first connecting the Meadow, since that's likely where folks will first hit it.

**Comment by AlexHedley** [comment]
Do you want the following added under Sections 1, 2 & 3?

> ## USB Cables
> It is important to remember that not all USB cables are created equal. When programming, Meadow uses a USB cable supplying both power and data. It is important to use a good quality USB cable to connect your Meadow device to your computer.
> Some USB cables are only suitable for charging as they do not contain the D+ and / or D- data lines.
> It is important to ensure that you have a USB cable capable of providing data transfer capability and that it is a good quality cable.

> ## Unpowered USB Hub
> If you’re having issues communicating with Meadow that is connected via an unpowered USB-Hub, try connecting Meadow directly to a USB port in your machine to ensure the USB-Hub is the issue.
> As there are a large variety USB-hubs out there, we cant guarantee Meadow will work properly for all of them.

**Comment by patridge** [comment]
Sorry we missed this reply. Yes, that's was the general idea we should summarize on the Deploying page. It can be super frustrating when nothing works simply because your cable is fighting you. I'll put something together.

**Comment by patridge** [comment]
[PR submitted](https://github.com/WildernessLabs/Documentation/pull/772)
