### ISSUE TITLE
broken link in Meadow.Foundation/Getting_Started

### ISSUE THREAD

**Issue by engunneer** [WildernessLabs/Documentation#586]
link should be ../../Getting_Started/ or ../../../Meadow/Getting_Started/ instead of ../../Meadow/Getting_Started/
https://github.com/WildernessLabs/Documentation/blob/4d7b2864a5a1579097a834bbed23126f9f5a7809/docs/Meadow/Meadow.Foundation/Getting_Started/index.md?plain=1#L9

**Comment by patridge** [comment]
Thank you for reporting this.

It looks like the old broken link was fixed, but I think the generic Getting_Started page was better. Submitted the above #770 PR to do that.
