### ISSUE TITLE
Class Ft232h doc says: Represents a DS3502 digital pot

### ISSUE THREAD

**Issue by E-R-T-W** [WildernessLabs/Documentation#618]
![image](https://github.com/WildernessLabs/Documentation/assets/129482880/93c8a218-404f-469f-9b3d-7b1683b1c603)

**Comment by patridge** [comment]
Thanks for reporting this! If it's this page in question, it looks like this issue has been resolved.

https://developer.wildernesslabs.co/docs/api/Meadow.Foundation/Meadow.Foundation.ICs.IOExpanders/Ft232h/
