### ISSUE TITLE
Code font is too small, and the padding is too large

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#73]
Implementation on left, design on right. Ignore the code colors.

<img width="1039" alt="screen shot 2018-01-28 at 1 44 59 pm" src="https://user-images.githubusercontent.com/947633/35487541-89cb228c-0431-11e8-900c-23a8b4ff0c1a.png">

**Comment by stephenkarpeles** [comment]
Bumped up font size for code & shrunk padding. Let me know if it still needs to change!

**Comment by bryancostanich** [comment]
Can we make the code sections scroll horizontally?

**Comment by stephenkarpeles** [comment]
Technically, we can... Though then they start to get a little crazy on mobile, because they require a good amount of horizontal scrolling. I could potentially get rid of the word-wrap on desktop, and force word-wrap on mobile to avoid that issue. Would that work okay?

**Comment by bryancostanich** [comment]
what do people usually do here?

the new font is too large anyway. my own fault. but it wraps horribly on desktop, too.

**Comment by stephenkarpeles** [comment]
Okay, I changed it up, and think it works better. Did the following:

- Shrunk the font a tad bit
- Removed word wrap
- Enabled horizontal scrolling (for both desktop and mobile)

I think it looks much better. Let me know though.

**Comment by bryancostanich** [comment]
Looks good.
