### ISSUE TITLE
Table styling is off

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#74]
wrong fonts, padding is too much.

<img width="1048" alt="screen shot 2018-01-28 at 1 46 17 pm" src="https://user-images.githubusercontent.com/947633/35487557-aca81062-0431-11e8-9e0f-69912de62b92.png">

**Comment by stephenkarpeles** [comment]
First TD of tables has the CourierPrime font now. In the Sketch mockup, only the first 'td' has this font, but I can make it be for the whole table if needed. Just let me know -- 

http://127.0.0.1:4002/Hardware/Tutorials/Electronics/Part4/Resistor_Tolerance/

**Comment by bryancostanich** [comment]
That only had courier prime because it was styled as code. sorry, i should have been more clear; it was the header row that had the font wrong, and the rest of the cells had padding issues. So the courier prime should be pulled off.
