### ISSUE TITLE
Home page images should appear under the heading in tablet/phone responsive sizes

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#78]
Right now, they're winding up under the bottom of the content:

<img width="768" alt="screen shot 2018-01-28 at 2 02 38 pm" src="https://user-images.githubusercontent.com/947633/35487770-247925ac-0434-11e8-867e-c5274d439b17.png">

**Comment by stephenkarpeles** [comment]
Images appearing under headings on mobile/tablet.

**Comment by bryancostanich** [comment]
Pulled latest on the stephenkarpeles branch and still seeing this:

<img width="759" alt="screen shot 2018-01-28 at 9 18 21 pm" src="https://user-images.githubusercontent.com/947633/35494654-e804b93c-0470-11e8-98b0-04b24db57e33.png">

**Comment by stephenkarpeles** [comment]
Just pushed another fix for this...

**Comment by bryancostanich** [comment]
Looks good, except for the Netduino.Foundation one:

<img width="778" alt="screen shot 2018-02-04 at 1 06 35 pm" src="https://user-images.githubusercontent.com/947633/35782402-491c26f2-09ac-11e8-9d1b-3577a5aeff52.png">

**Comment by stephenkarpeles** [comment]
Okay. Should be updated.
