### ISSUE TITLE
F7 Feather can not be recognized on Surface Pro 8 for some reason

### ISSUE THREAD

**Issue by sergiibielskyi** [WildernessLabs/Documentation#783]
Hey,
I just received hack kit from meadow. I am trying to connect MCU via USB. When I connect such a device to the laptop I see a blue light near BOOT button. I follow the instruction to deploy OS https://developer.wildernesslabs.co/Meadow/Getting_Started/Deploying_Meadow.OS/ I do not see any new STM32 BOOTLOADER or USB Serial Device (COMX) in Device Manager. I changed and used different interfaces. What am I doing wrong? )

**Comment by jorgedevs** [comment]
HI Sergii,

If you connect your board just regular (not holding BOOT button). Does a new COM port show up in the Device Manager?

**Comment by sergiibielskyi** [comment]
Hey, when I connect device, there is nothing changed in device manager (

**Comment by jorgedevs** [comment]
If you're still having issues, I suggest you join our [Public Slack](http://slackinvite.wildernesslabs.co/) channel. It'll be easier to help you there directly.
