### ISSUE TITLE
SubNav doesn't response well

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#79]
It should probably stack. right now, it just squishes:

<img width="755" alt="screen shot 2018-01-28 at 2 02 41 pm" src="https://user-images.githubusercontent.com/947633/35487779-42d89f3c-0434-11e8-9c06-ed8438beea1f.png">

**Comment by stephenkarpeles** [comment]
This should be all set. Added some spacing until tablet viewport, and then stack them up on smaller screens.
