### ISSUE TITLE
Footer links should stack in mobile responsive size

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#81]
they should stack to make room for the logo on left. right now, they squish:

<img width="528" alt="screen shot 2018-01-28 at 2 07 15 pm" src="https://user-images.githubusercontent.com/947633/35487808-a0600eb0-0434-11e8-98f1-816837b310cb.png">

**Comment by stephenkarpeles** [comment]
Columns stacking on mobile.

**Comment by bryancostanich** [comment]
Looks good, but on tablet they also stack. Maybe there is some in between for tablet?

**Comment by bryancostanich** [comment]
Looks great.
