### ISSUE TITLE
Add USB Cable issues to troubleshooting page.

### ISSUE THREAD

**Issue by bryancostanich** [WildernessLabs/Documentation#92]
from the forums:

Bryan, if you ever do that troubleshooting page, please, explain the USBcable issue. I get that some cables can power, but not transfer data, either because the data lines are broken or the darn cable was built to only power or charge in the first place. But is there a possibility that a faulty cable appears to work? It can succeed in making the Netduino recognisable for the computer, it can transfer parts of the data and then refuses to send something else?

**Comment by jorgedevs** [comment]
Closing this issue, as we have a "USB Cables" section in our [troubleshooting](http://developer.wildernesslabs.co/Meadow/Meadow_Basics/Troubleshooting/) site.
