### ISSUE TITLE
Fix documentation error

### ISSUE THREAD

**Issue by ncarandini** [WildernessLabs/Documentation#95]
On page [Part 1 - Physics of Electricity | Electrical Current](http://developer.wildernesslabs.co/Hardware/Tutorials/Electronics/Part1/Electrical_Current/) at the end of the section "Achieving Balance" the text "[…] which can mean either a positive charge (`electron`) or a negative charge (`hole`)." has to be replaced with "[…] a positive charge (`hole`) or a negative charge (`electron`)."

**Comment by bryancostanich** [comment]
Looks like this got fixed along the way. Thanks for reporting!
